services:
  dev:
    hostname: dev
    container_name: proxy-rs-dev-container
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/iroh-proxy:cached
    command: sleep infinity
    stop_signal: SIGKILL

